export default {
  name: '30 seconds of code',
  dirName: '30code',
  repoUrl: 'https://github.com/30-seconds/30-seconds-of-code',
  snippetPath: 'snippets',
  requirables: [
    'snippet_data/snippets.json',
  ],
  slug: 'js',
  reducer: 'es6Reducer',
  featured: 1,
  theme: {
    backColor: '#f6d854',
    foreColor: '#392f31',
  },
  biasPenaltyMultiplier: 1.02,
  tagScores: {
    'array': 5,
    'promise': 5,
    'object': 4,
    'function': 4,
    'event': 4,
    'string': 3,
    'date': 3,
    'css': 3,
    'browser': 2,
    'node': 2,
    'regexp': 2,
    'adapter': 1,
    'math': 1,
    'utility': 1,
    'type': 1,
    'url': 1,
    'recursion': 1,
    'json': 1,
    'random': 1,
  },
  keywordScores: {
    'reduce': 5,
    'map': 5,
    'filter': 5,
    'spread': 4,
    'array': 4,
    'date': 4,
    'destructuring': 4,
    'join': 4,
    'foreach': 3,
    'substring': 3,
    'replace': 3,
    'function': 3,
    'splice': 2,
    'slice': 2,
    'bind': 2,
    'async': 2,
    'await': 2,
    'timeout': 1,
  },
};
