export default {
  name: '30 seconds of CSS',
  dirName: '30css',
  repoUrl: 'https://github.com/30-seconds/30-seconds-of-css',
  snippetPath: 'snippets',
  requirables: [
    'snippet_data/snippets.json',
  ],
  slug: 'css',
  reducer: 'cssReducer',
  resolver: 'cssResolver',
  featured: 3,
  theme: {
    backColor: '#3f4de4',
    foreColor: '#ffffff',
  },
  biasPenaltyMultiplier: 1.02,
  tagScores: {
    'animation': 5,
    'layout': 4,
    'visual': 3,
    'interactivity': 2,
    'other': 1,
  },
  keywordScores: {
    'flex': 5,
    'grid': 5,
    'animation': 4,
    'shadow': 4,
    'padding': 3,
    'margin:': 3,
    'important': 3,
    'overflow': 2,
    'hover': 2,
    'border': 2,
    'transition': 2,
    'display': 1,
    'button': 1,
    'color': 1,
    'background': 1,
    'selector': 1,
    'javascript': 1,
    'center': 1,
  },
};
