export default {
  name: '30 seconds of PHP',
  dirName: '30php',
  repoUrl: 'https://github.com/30-seconds/30-seconds-of-php',
  snippetPath: 'snippets',
  requirables: [
    'snippet_data/snippets.json',
  ],
  slug: 'php',
  biasPenaltyMultiplier: 1.06,
  tagScores: {
    'array': 5,
    'string': 3,
    'math': 3,
    'function': 2,
  },
  keywordScores: {
    'explode': 5,
    'map': 5,
    'merge': 4,
    'push': 3,
    'filter': 3,
    'foreach': 3,
    'array': 3,
    'substr': 2,
    'get': 2,
    'type': 2,
    'keys': 2,
    'replace': 2,
    'date': 1,
    'include': 1,
    'redirect': 1,
    'loop': 1,
    'json': 1,
    'object': 1,
  },
};
