require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rake
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'node_modules/**/*'
    - 'dist/**/*'
    - 'parsley/**/*'
    - 'imported/**/*'
    - 'tmp/**/*'
    - 'astro/**/*'
    - 'vendor/**/*'
    - '.content/**/*'
    - '.astro/**/*'
    - '.github/**/*'
    - '.vscode/**/*'

Metrics:
  Enabled: false

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Layout/BeginEndAlignment:
  Enabled: false

Layout/BlockAlignment:
  Enabled: false

Layout/BlockEndNewline:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'Gemfile'

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineContinuationLeadingSpace:
  Enabled: false

Layout/LineContinuationSpacing:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/MultilineBlockLayout:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false
###

Lint/EmptyClass:
  AllowComments: true

Lint/FloatComparison:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/NoReturnInBeginEndBlocks:
  Enabled: false

Lint/NonAtomicFileOperation:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Lint/SymbolConversion:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessAccessModifier:
  ContextCreatingMethods:
    - class_methods
    - concerning
    - has_many

Lint/UselessAssignment:
  Exclude:
    - "spec/**/*"

Lint/Void:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Performance/CollectionLiteralInLoop:
  Enabled: false

Performance/Count:
  Enabled: false

Performance/Detect:
  Enabled: false

Performance/InefficientHashSearch:
  Enabled: false

Performance/MapCompact:
  Enabled: false

Performance/RedundantMerge:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

Performance/StringIdentifierArgument:
  Enabled: false

Performance/StringInclude:
  Enabled: false

Performance/StringReplacement:
  Enabled: false

Performance/Sum:
  Enabled: false

Performance/TimesMap:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/Be:
  Enabled: false

RSpec/BeEq:
  Enabled: false

RSpec/BeNil:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/ClassCheck:
  Enabled: false

RSpec/ContextMethod:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ExampleLength:
  Max: 103

RSpec/ExampleWording:
  Enabled: false

RSpec/ExcessiveDocstringSpacing:
  Enabled: false

RSpec/ExpectChange:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/LetBeforeExamples:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 31

RSpec/MultipleMemoizedHelpers:
  Max: 123

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 12

RSpec/NoExpectationExample:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: not_to

RSpec/OverwritingSetup:
  Enabled: false

RSpec/PendingWithoutReason:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

RSpec/RepeatedExample:
  Enabled: false

RSpec/RepeatedExampleGroupBody:
  Enabled: false

RSpec/RepeatedExampleGroupDescription:
  Enabled: false

RSpec/ReturnFromStub:
  Enabled: false

RSpec/ScatteredLet:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

RSpec/SortMetadata:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/SubjectDeclaration:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Rails/ActionOrder:
  Enabled: false

Rails/ActiveRecordCallbacksOrder:
  Enabled: false

Rails/CompactBlank:
  Enabled: false

Rails/ContentTag:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/ExpandedDateRange:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/FindBy:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/HttpStatus:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/IndexBy:
  Enabled: false

Rails/IndexWith:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/LinkToBlank:
  Enabled: false

Rails/NegateInclude:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/Pick:
  Enabled: false

Rails/Pluck:
  Enabled: false

Rails/RedundantForeignKey:
  Enabled: false

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/RootPathnameMethods:
  Enabled: false

Rails/RootPublicPath:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/ToSWithArgument:
  Enabled: false

Rails/UnknownEnv:
  Enabled: false

Rails/Validation:
  Enabled: false

Rails/WhereEquals:
  Enabled: false

Rails/WhereExists:
  Enabled: false

Rails/WhereNot:
  Enabled: false

Rake/Desc:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/Alias:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/ArrayIntersect:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/ConcatArrayLiterals:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - 'Rakefile'
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/setup'

Style/ExplicitBlockArgument:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/FloatDivision:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'config.ru'

Style/GuardClause:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/HashConversion:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashLikeCase:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/HashTransformValues:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/MapToHash:
  Enabled: false

Style/MapToSet:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/NegatedIf:
  EnforcedStyle: postfix

Style/NegatedIfElseCondition:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 11

Style/NumericPredicate:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/QuotedSymbols:
  Enabled: false

Style/RedundantArgument:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Enabled: false

Style/RedundantFreeze:
  Enabled: false

Style/RedundantLineContinuation:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/RedundantStringEscape:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SingleArgumentDig:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
